<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.4" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.4"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.4"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.4"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.4"/>
        <PackageReference Include="HeroIcons.Avalonia" Version="1.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
        <PackageReference Include="ReactiveUI" Version="20.1.63" />
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.1.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpHook.Reactive" Version="5.3.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nulah.Shortcuts.Core\Nulah.Shortcuts.Core.csproj" />
      <ProjectReference Include="..\Nulah.Shortcuts.Domain\Nulah.Shortcuts.Domain.csproj" />
    </ItemGroup>
</Project>
